language: csharp
dist: xenial
mono: none
dotnet: 2.2.104

os:
 - linux
 - osx
install:
 - dotnet restore
script:
 - dotnet build
 - dotnet test 2-test/Chat.Client.Library.Tests.csproj
notifications:
  email: false