# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix: 
    Ubuntu: 
	  imagenName: 'ubuntu-16.04'
	Visual Studio 2019:
	  imagenName: 'windows-2019'
	High Sierra:
	  imageName: 'macos-10.13'
  
pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  displayName: "Nuget Restore"
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: "Nuget Build"
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: "Nuget Test"
  inputs:
    command: 'test'