name: CI

on: [push]

jobs:
  build:
  
  strategy:
   matrix:
    agent: ['windows-latest','ubuntu-latest','macos-latest']
  runs-on: ${{matrix.agent}}
  name: Integration in ${{matrix.agent}}
  
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '2.2.108'
  - run: dotnet build "Chat.sln"
  - run: dotnet test "Chat.sln"
